/*
 * Ambulance documentation Api
 *
 * Ambulance documentation
 *
 * API version: 1.0.0
 * Contact: xnemecm1@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

 package doc_doc_webapi

import (
   "net/http"

   "github.com/gin-gonic/gin"
)

type DocsAPI interface {

   // internal registration of api routes
   addRoutes(routerGroup *gin.RouterGroup)

    // AddDocument - Add a new document
   AddDocument(ctx *gin.Context)

    // DeleteDocument - Delete a document
   DeleteDocument(ctx *gin.Context)

    // GetDocumentById - Get a document by ID
   GetDocumentById(ctx *gin.Context)

    // GetDocuments - Get all documents
   GetDocuments(ctx *gin.Context)

    // UpdateDocument - Update a document
   UpdateDocument(ctx *gin.Context)

 }

 // partial implementation of DocsAPI - all functions must be implemented in add on files
type implDocsAPI struct {

}

func newDocsAPI() DocsAPI {
  return &implDocsAPI{}
}

func (this *implDocsAPI) addRoutes(routerGroup *gin.RouterGroup) {
  routerGroup.Handle( http.MethodPost, "/doc", this.AddDocument)
  routerGroup.Handle( http.MethodDelete, "/doc/:id", this.DeleteDocument)
  routerGroup.Handle( http.MethodGet, "/doc/:id", this.GetDocumentById)
  routerGroup.Handle( http.MethodGet, "/doc", this.GetDocuments)
  routerGroup.Handle( http.MethodPut, "/doc/:id", this.UpdateDocument)
}


// Copy following section to separate file, uncomment, and implement accordingly
