/*
 * Ambulance documentation Api
 *
 * Ambulance documentation
 *
 * API version: 1.0.0
 * Contact: xnemecm1@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package doc_doc_webapi

type Document struct {

	Id int64 `json:"id"`

	Title string `json:"title"`

	Patient string `json:"patient"`

	Date string `json:"date"`

	Report string `json:"report"`
}
