/*
 * Ambulance documentation Api
 *
 * Ambulance documentation
 *
 * API version: 1.0.0
 * Contact: xnemecm1@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package doc_doc_webapi

import (
    "github.com/gin-gonic/gin"
)

func AddRoutes(engine *gin.Engine) {
  group := engine.Group("/api")
  
  {
    api := newDocsAPI()
    api.addRoutes(group)
  }
  
}