openapi: 3.0.0
servers:
  - description: Cluster Endpoint
    url: /api
info:
  description: Ambulance documentation
  version: "1.0.0"
  title: Ambulance documentation Api
  contact:
    email: xnemecm1@stuba.sk
  license:
    name: CC BY 4.0
    url: "https://creativecommons.org/licenses/by/4.0/"
tags:
 - name: docs
   description: Ambulance documentation
paths:
  /docs:
    get:
      tags:
        - docs
      summary: Get all documents
      operationId: getDocuments
      responses:
        '200':
          description: A list of documents
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Document'
  /doc:
    post:
      tags:
        - docs
      summary: Add a new document
      operationId: addDocument
      requestBody:
        description: Document to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Document'
      responses:
        '200':
          description: Document created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
  /doc/{id}:
    get:
      tags:
        - docs
      summary: Get a document by ID
      operationId: getDocumentById
      parameters:
        - name: id
          in: path
          description: ID of document to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A document
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
        '404':
          description: Document not found
    put:
      tags:
        - docs
      summary: Update a document
      operationId: updateDocument
      parameters:
        - name: id
          in: path
          description: ID of document to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Document to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Document'
      responses:
        '200':
          description: Document updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
        '404':
          description: Document not found
    delete:
      tags:
        - docs
      summary: Delete a document
      operationId: deleteDocument
      parameters:
        - name: id
          in: path
          description: ID of document to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Document deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
        '404':
          description: Document not found
components:
  schemas:
    Document:
      type: object
      required: [id, title, patient, date, report]
      properties:
        id:
          type: string
          example: "x123xf"
        title:
          type: string
          example: "Patient report"
        patient:
          type: string
          example: "John Doe"
        date:
          type: string
          example: "2021-05-12"
        report:
          type: string
          example: "Patient was brought to the hospital with a broken leg."
